""" 
Problem 29

Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

22=4, 23=8, 24=16, 25=32
32=9, 33=27, 34=81, 35=243
42=16, 43=64, 44=256, 45=1024
52=25, 53=125, 54=625, 55=3125
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

"""

import time
import math


def calculate() -> int:
    a = 100
    b = 100
    values = get_list_of_powers(a, b)
    unique_values = list(set(values))
    unique_values.sort()
    return len(unique_values)


def get_list_of_powers(a, b) -> list:
    output = []
    for i in range(2, a + 1):
        for j in range(2, b + 1):
            output.append(int(math.pow(i, j)))
    return output


if __name__ == "__main__":
    start_time = time.time()
    print(f"The answer to Problem 29 is {calculate()}")
    end_time = time.time()
    print(f"This solution took {end_time - start_time} seconds to run")
